{% set name = "geometry-central" %}
{% set version = "0.1.0.2024.10.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nmwsharp/geometry-central/archive/70c859ec3b58fe597c0063673a74082654e9c5aa.zip
  sha256: e13aa61181935d4f9c20985a93fa1ef2b8df2cd20e7f357c16919dc4e2607cb6

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - eigen >=3.3
    - happly

test:
  commands:
    - test -f ${PREFIX}/lib/libgeometry-central.so  # [linux]
    - test -f ${PREFIX}/lib/libgeometry-central.dylib  # [osx]
    - if not exist %LIBRARY_BIN%\\libgeometry-central.dll exit 1  # [win]

about:
  home: https://github.com/nmwsharp/geometry-central
  summary: Geometry-central is a modern C++ library of data structures and algorithms for geometry processing, with a particular focus on surface meshes.
  license: MIT AND BSD-2-Clause
  license_file:
    - LICENSE
    - LICENSE_nanoflann  # BSD-2-Clause
    - LICENSE_nanort  # MIT

extra:
  recipe-maintainers:
    - ytausch
